In [28]:
import numpy as np
x = np.array([[1, 0],
              [0, 1]])
h = np.array([[1,2,1],[2,1,3],[4,2,1]])

print(x)
print(h)

[[1 0]
 [0 1]]
[[1 2 1]
 [2 1 3]
 [4 2 1]]


In [29]:
import scipy.signal as sg
 
convolve = sg.convolve(x, h)
print(convolve) 

[[1 2 1 0]
 [2 2 5 1]
 [4 4 2 3]
 [0 4 2 1]]


In [30]:
print(sg.convolve2d(h, x, mode='same'))

[[1 2 1]
 [2 2 5]
 [4 4 2]]


In [31]:
print(signal.convolve2d(h, x, mode='full'))

[[1 2 1 0]
 [2 2 5 1]
 [4 4 2 3]
 [0 4 2 1]]


In [32]:
print(signal.convolve2d(h, x, mode='valid'))

[[2 5]
 [4 2]]
